# Generated by Django 6.0.4 on 2026-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="business_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_business_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
