# Generated by Django 6.0.5 on 2026-06-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_business_payment_notice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='core_sale_busines_e84c6d_idx',
            old_name='core_sale_busines_0b0e0d_idx',
        ),
        migrations.AlterField(
            model_name='item',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.business'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.business'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.business'),
        ),
    ]
