# Generated by GitHub Copilot

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyMLReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("report_data", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeklymlreports",
                        to="core.business",
                    ),
                ),
            ],
            options={
                "unique_together": {("business", "week_start_date")},
                "ordering": ["-week_start_date"],
            },
        ),
    ]
